/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Atividade atividade = new Atividade("Minha atividade");
        Tarefa tarefa1 = new Tarefa("Tarefa 1", "Descrição da tarefa 1", Priority.NORMAL, new Date(), 5);
        Tarefa tarefa2 = new Tarefa("Tarefa 2", "Descrição da tarefa 2", Priority.ALTA, new Date(), 8);

        atividade.adicionarTarefa(tarefa1);
        atividade.adicionarTarefa(tarefa2);

        System.out.println("Listagem de todas as tarefas:");
        List<Tarefa> todasTarefas = atividade.listarTarefas();
        for (Tarefa tarefa : todasTarefas) {
            System.out.println(tarefa.getAssunto());
        }

        System.out.println("\nListagem de todas as tarefas pendentes:");
        List<Tarefa> tarefasPendentes = atividade.listarTarefasPendentes();
        for (Tarefa tarefa : tarefasPendentes) {
            System.out.println(tarefa.getAssunto());
        }
    }
}
